services:
  minio:
    # image: minio/minio:latest
    build:
      context: .
    # command: server /data --console-address ":9001"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      MINIO_ROOT_USER: pyrite
      MINIO_ROOT_PASSWORD: minio
      MINIO_SERVER_URL: http://127.0.0.1.nip.io
      MINIO_BROWSER_REDIRECT_URL: http://127.0.0.1.nip.io/minio/ui
