services:
  minio:
    build:
      context: .
    # command: server /data --console-address ":9001"
    ports:
      - "80:80"
    # volumes:
    #   - ./data:/data
    environment:
      MINIO_ROOT_USER: pyrite
      MINIO_ROOT_PASSWORD: minio@pyrite
      MINIO_SERVER_URL: http://127.0.0.1.nip.io
      MINIO_BROWSER_REDIRECT_URL: http://127.0.0.1.nip.io/minio/ui
