services:
  minio:
    build:
      context: .
    command: server /data --console-address ":9001"
    ports:
      - "80:80"
    environment:
      MINIO_ROOT_USER: pyritepyrite
      MINIO_ROOT_PASSWORD: miniopyrite
      MINIO_SERVER_URL: http://127.0.0.1.nip.io
      MINIO_BROWSER_REDIRECT_URL: http://127.0.0.1.nip.io/minio/ui
