name: Build and Publish Images with apko

on:
  push:
    branches:
      - develop

    paths:
      - "containers/**/*.yaml"
      - ".github/workflows/release.yaml"
  workflow_dispatch: # Allow manual triggering

permissions:
  packages: write

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: containers
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone for faster checkout

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Generate matrix
        id: generate
        run: |
          # Find all YAML files and process them into a JSON array
          json_array=$(find . -type f -name "*.yaml" ! -path "*/_*" | sort | while read -r file; do
              IMAGE_NAME=$(dirname "$file" | sed "s/^\.\///" | tr "/" "-")
              TAG_NAME=$(basename "$file" .yaml)
              FILEPATH="${file#./}"

              # Output JSON object for this file
              jq -n --arg image "$IMAGE_NAME" --arg tag "$TAG_NAME" --arg filepath "$FILEPATH" \
                  '{image: $image, tag: $tag, filepath: $filepath}'
          done | jq -s .)

          # Create the final matrix object
          matrix=$(echo "$json_array" | jq -c '.')

          # Write to GitHub output
          echo "matrix=$matrix" >>$GITHUB_OUTPUT

          # For debugging
          echo "Generated Matrix:"
          cat $GITHUB_OUTPUT

          echo "Formatted matrix for review:"
          echo "$matrix" | jq '.'

  process-images:
    needs: generate-matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: containers
    strategy:
      matrix:
        registry: ["ghcr.io"]
        # registry: ["ttl.sh"]
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      max-parallel: 5
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      # - name: Configure Docker Hub credentials
      #   if: matrix.registry == 'docker.io'
      #   run: |
      #     echo "REGISTRY_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
      #     echo "REGISTRY_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV
      #     echo "REGISTRY_PREFIX=${{ secrets.DOCKERHUB_USERNAME }}/" >> $GITHUB_ENV
      #     echo "FULL_IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ matrix.tag }}" >> $GITHUB_ENV

      - name: Configure GitHub Container Registry credentials
        if: matrix.registry == 'ghcr.io'
        run: |
          echo "REGISTRY_USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "REGISTRY_PREFIX=pyritecloud" >> $GITHUB_ENV
          echo "FULL_IMAGE_NAME=ghcr.io/pyritecloud/${{ matrix.image }}:${{ matrix.tag }}" >> $GITHUB_ENV

      - name: Publish Image with apko
        id: publish
        uses: distroless/actions/apko-publish@main
        with:
          config: ./containers/${{ matrix.filepath }}
          tag: ${{ env.FULL_IMAGE_NAME }}
          repository_owner: ${{ env.REGISTRY_USERNAME }}
          token: ${{ env.REGISTRY_PASSWORD }}

      # - name: Sign Image
      #   shell: bash
      #   run: |
      #     COSIGN_EXPERIMENTAL=true cosign sign ${{ steps.publish.outputs.digest }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FULL_IMAGE_NAME }}
          format: "table"
          exit-code: "0"
          severity: "CRITICAL,HIGH"
